repos:
  - repo: git@github.com:nametake/pre-commit-buf.git
    rev: v2.0.0
    hooks:
      - id: buf-lint
      - id: buf-breaking
        args: [ .git#branch=master ] # required --against-input arg
